### ISSUE TITLE
-x flag is silently ignored in YAML mode

### ISSUE THREAD

**Issue by justaddcoffee** [TheJacksonLaboratory/LIRICAL#461]
A minor issue, but conflicting commandline args for prefix is ignored in YAML mode. 

For example, using the command and YAML below, the -x flag is silently ignored, and this file is output:
`label_from_yaml.html`
The `-x` flag should probably should either override the YAML and produce this file: `label_from_command_line.html`
or emit a warning message saying the -x flag conflicts with the YAML prefix setting.

`java -jar target/LIRICAL.jar yaml -y ./example_data/x_flag_issue/x_flag_issue.yml -x label_from_command_line`

```
---
analysis:
  genomeAssembly: hg19
  vcf: /Users/jtr4v/IdeaProjects/LIRICAL/example_data/pfeiffer/Pfeiffer.vcf
  exomiser: /Users/jtr4v/IdeaProjects/LIRICAL/data/1909_hg19
  transcriptdb: ensembl
hpoIds: ['HP:0001875', 'HP:0031508', 'HP:0002970','HP:0100864','HP:0008450','HP:0001156','HP:0100866']
prefix: label_from_yaml
```
