### ISSUE TITLE
Yaml file don't work when using

### ISSUE THREAD

**Issue by gulipeng17** [TheJacksonLaboratory/LIRICAL#617]
Hi ,Doctor:
    My comd is   lirical-cli-2.0.0-RC2.jar yaml -y LDS2.yaml ，but the tools arise "ERROR o.m.l.c.c.AbstractPrioritizeCommand - Error: java.lang.NullPointerException: Cannot invoke "org.monarchinitiative.lirical.core.io.VariantParser.sampleNames()" because "variantParser" is null"
    My yaml file is   the demo you provided :
              ---
              sampleId: Patient 4
              hpoIds: ['HP:0001659', 'HP:0001166', 'HP:0001631', 'HP:0000193', 'HP:0012385', 'HP:0011645', 'HP:0000272',
                       'HP:0000347', 'HP:0001655', 'HP:0000768', 'HP:0004927', 'HP:0002650', 'HP:0001704']
              # negatedHpoIds: []
              age: P9Y
              sex: FEMALE
              # Set real path to a VCF file
              vcf: LDS2.vcf.gz

    What should I do next

**Comment by ielis** [comment]
Hi @gulipeng17 
can you try the same with the following YAML file?
```yaml
## LIRICAL Analysis Template.
# These are all the possible options for running LIRICAL. Use this as a template for your own set-up.
---
sampleId: Patient 4
hpoIds: ['HP:0001659', 'HP:0001166', 'HP:0001631', 'HP:0000193', 'HP:0012385', 'HP:0011645', 'HP:0000272',
         'HP:0000347', 'HP:0001655', 'HP:0000768', 'HP:0004927', 'HP:0002650', 'HP:0001704']
# negatedHpoIds: []
age: P9Y
sex: FEMALE
# Set real path to a VCF file. For instance, path to the example `LDS2.vcf.gz` file located next to this YAML config.
# vcf: /path/to/LDS2.vcf.gz

```
